#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Web application installer');
$app->add(new Glamorous\Boiler\SetupPathCommand);
$app->add(new Glamorous\Boiler\RemovePathCommand);
$app->add(new Glamorous\Boiler\GetPathsCommand);
$app->add(new Glamorous\Boiler\RunCommand);

$app->run();
